// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGTw8mK7s7j5ODXitBcrpjonhbSxsKK-s',
    appId: '1:813695073093:web:1be2a9c03a800d0d015c2c',
    messagingSenderId: '813695073093',
    projectId: 'flutter-zoom-b83e4',
    authDomain: 'flutter-zoom-b83e4.firebaseapp.com',
    storageBucket: 'flutter-zoom-b83e4.appspot.com',
    measurementId: 'G-L22CWYDB8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX6R0tkGdlP2veFTsDuGYofa1r8LrVN44',
    appId: '1:813695073093:android:d2e68c066f016f73015c2c',
    messagingSenderId: '813695073093',
    projectId: 'flutter-zoom-b83e4',
    storageBucket: 'flutter-zoom-b83e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATLIfAl2m8ttrjxCeoWZnoGnUWVSQz-CU',
    appId: '1:813695073093:ios:4c0395ce3fd2fab5015c2c',
    messagingSenderId: '813695073093',
    projectId: 'flutter-zoom-b83e4',
    storageBucket: 'flutter-zoom-b83e4.appspot.com',
    androidClientId: '813695073093-sj9cvkmuig0pndsbeiattgucc0nahq2m.apps.googleusercontent.com',
    iosClientId: '813695073093-92psv1iu20vp574j6c2vhvk18sdetjh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterZoom',
  );
}
